// app/src/screens/CheckIn.tsx
import React, { useState, useCallback, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TextInput,
  Pressable,
  StyleSheet,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Animated, {
  FadeIn,
  FadeInDown,
  FadeOut,
  Layout,
} from 'react-native-reanimated';
import { colors, spacing, radius, shadows, typography } from '../styles/theme';
import useCheckIn, {
  CHECKIN_DIMENSIONS,
  type CheckInRecord,
} from '../hooks/useCheckIn';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';

// ========================
// 类型定义
// ========================

type DashboardStackParamList = {
  Dashboard: undefined;
  CheckIn: undefined;
  WRAPPlan: undefined;
};

type CheckInScreenProps = NativeStackScreenProps<
  DashboardStackParamList,
  'CheckIn'
>;

interface DimensionConfig {
  key: string;
  label: string;
  icon: string;
  left: string;
  right: string;
}

// ========================
// 常量
// ========================

const DIMENSIONS: DimensionConfig[] = [
  { key: 'sleep', label: '睡眠质量', icon: '\uD83D\uDE34', left: '很差', right: '很好' },
  { key: 'mood', label: '情绪状态', icon: '\uD83D\uDE0A', left: '低落', right: '愉悦' },
  { key: 'body', label: '身体活力', icon: '\uD83C\uDFC3', left: '疲惫', right: '充沛' },
  { key: 'motivation', label: '动力水平', icon: '\uD83C\uDFAF', left: '无', right: '强烈' },
  { key: 'cognition', label: '思维清晰度', icon: '\uD83E\uDDE0', left: '模糊', right: '清晰' },
  { key: 'social', label: '社交意愿', icon: '\uD83D\uDC65', left: '回避', right: '主动' },
];

const ENCOURAGEMENTS = [
  '\u2705 签到成功！记录是康复的第一步 \uD83D\uDCAA',
  '\uD83C\uDF1F 很好！你正在了解自己',
  '\uD83C\uDF31 每一天的记录都是成长的种子',
  '\uD83D\uDCAA 你做得很好，继续保持！',
  '\uD83C\uDF08 感谢你花时间关注自己',
];

const MAX_NOTE_LENGTH = 200;

// ========================
// 子组件: RatingButton
// ========================

interface RatingButtonProps {
  value: number;
  selected: boolean;
  onPress: (val: number) => void;
}

function RatingButton({ value, selected, onPress }: RatingButtonProps) {
  return (
    <Pressable
      onPress={() => onPress(value)}
      style={({ pressed }) => [
        styles.ratingButton,
        selected && styles.ratingButtonSelected,
        pressed && styles.ratingButtonPressed,
      ]}
    >
      <Text
        style={[
          styles.ratingButtonText,
          selected && styles.ratingButtonTextSelected,
        ]}
      >
        {value}
      </Text>
    </Pressable>
  );
}

// ========================
// 子组件: DimensionGroup
// ========================

interface DimensionGroupProps {
  dim: DimensionConfig;
  value: number | undefined;
  onSelect: (key: string, val: number) => void;
  index: number;
}

function DimensionGroup({ dim, value, onSelect, index }: DimensionGroupProps) {
  return (
    <Animated.View
      entering={FadeInDown.delay(index * 60).duration(400)}
      style={styles.dimGroup}
    >
      <View style={styles.dimLabel}>
        <Text style={styles.dimIcon}>{dim.icon}</Text>
        <Text style={styles.dimLabelText}>{dim.label}</Text>
      </View>
      <View style={styles.ratingRow}>
        <View style={styles.ratingGroup}>
          {[1, 2, 3, 4, 5].map((val) => (
            <RatingButton
              key={val}
              value={val}
              selected={value === val}
              onPress={(v) => onSelect(dim.key, v)}
            />
          ))}
        </View>
      </View>
      <View style={styles.ratingLabels}>
        <Text style={styles.ratingLabelLeft}>{dim.left}</Text>
        <Text style={styles.ratingLabelRight}>{dim.right}</Text>
      </View>
    </Animated.View>
  );
}

// ========================
// 子组件: DoneCard
// ========================

interface DoneCardProps {
  icon: string;
  title: string;
  desc: string;
  buttonLabel?: string;
  onButtonPress?: () => void;
}

function DoneCard({ icon, title, desc, buttonLabel, onButtonPress }: DoneCardProps) {
  return (
    <Animated.View
      entering={FadeIn.duration(500)}
      style={styles.doneCard}
    >
      <Text style={styles.doneIcon}>{icon}</Text>
      <Text style={styles.doneTitle}>{title}</Text>
      <Text style={styles.doneDesc}>{desc}</Text>
      {buttonLabel && onButtonPress && (
        <Pressable
          onPress={onButtonPress}
          style={({ pressed }) => [
            styles.reEditButton,
            pressed && styles.buttonPressed,
          ]}
        >
          <Text style={styles.reEditButtonText}>{buttonLabel}</Text>
        </Pressable>
      )}
    </Animated.View>
  );
}

// ========================
// 主组件: CheckIn
// ========================

export default function CheckIn({ navigation }: CheckInScreenProps) {
  const { checkIns, addCheckIn, updateCheckIn, getTodayCheckIn } = useCheckIn();
  const todayCheckIn = getTodayCheckIn();
  const hasCheckedToday = !!todayCheckIn;

  const [ratings, setRatings] = useState<Record<string, number>>({});
  const [note, setNote] = useState('');
  const [editing, setEditing] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [encouragement, setEncouragement] = useState('');

  // 进入编辑模式时回填已有数据
  useEffect(() => {
    if (editing && todayCheckIn) {
      setRatings(todayCheckIn.dimensions || {});
      setNote(todayCheckIn.note || '');
    }
  }, [editing, todayCheckIn]);

  const allRated = DIMENSIONS.every((d) => ratings[d.key]);

  const selectRating = useCallback((key: string, val: number) => {
    setRatings((prev) => ({ ...prev, [key]: val }));
  }, []);

  const handleSubmit = useCallback(() => {
    if (!allRated) return;

    if (editing && todayCheckIn) {
      updateCheckIn(todayCheckIn.date, ratings, note);
    } else {
      addCheckIn(ratings, note);
    }

    setSubmitted(true);
    setEditing(false);
    setEncouragement(
      ENCOURAGEMENTS[Math.floor(Math.random() * ENCOURAGEMENTS.length)],
    );
  }, [allRated, ratings, note, editing, todayCheckIn, addCheckIn, updateCheckIn]);

  const handleEdit = useCallback(() => {
    setEditing(true);
    setSubmitted(false);
  }, []);

  const handleGoBack = useCallback(() => {
    navigation.goBack();
  }, [navigation]);

  // 已签到且未进入编辑模式：显示已签到卡片
  if (hasCheckedToday && !editing && !submitted) {
    return (
      <SafeAreaView style={styles.safeArea} edges={['top']}>
        <View style={styles.container}>
          {/* 头部 */}
          <View style={styles.header}>
            <Text style={styles.headerTitle}>每日签到 {'\uD83D\uDCCB'}</Text>
            <Text style={styles.headerSubtitle}>今日签到记录</Text>
          </View>

          <View style={styles.content}>
            <DoneCard
              icon={'\u2705'}
              title="今日已签到"
              desc="你今天已经完成了签到，可以修改或明天继续加油！"
              buttonLabel="修改今日签到"
              onButtonPress={handleEdit}
            />
          </View>
        </View>
      </SafeAreaView>
    );
  }

  // 提交成功后
  if (submitted) {
    return (
      <SafeAreaView style={styles.safeArea} edges={['top']}>
        <View style={styles.container}>
          {/* 头部 */}
          <View style={styles.header}>
            <Text style={styles.headerTitle}>每日签到 {'\uD83D\uDCCB'}</Text>
          </View>

          <View style={styles.content}>
            <DoneCard
              icon={'\uD83C\uDF89'}
              title={editing ? '修改成功！' : '签到完成！'}
              desc={encouragement}
            />

            <Pressable
              onPress={handleGoBack}
              style={({ pressed }) => [
                styles.backButton,
                pressed && styles.buttonPressed,
              ]}
            >
              <Text style={styles.backButtonText}>返回</Text>
            </Pressable>
          </View>
        </View>
      </SafeAreaView>
    );
  }

  // 签到表单
  return (
    <SafeAreaView style={styles.safeArea} edges={['top']}>
      <KeyboardAvoidingView
        style={styles.keyboardAvoid}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      >
        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          bounces={true}
          keyboardShouldPersistTaps="handled"
        >
          {/* 头部 */}
          <Animated.View entering={FadeIn.duration(400)} style={styles.header}>
            <Text style={styles.headerTitle}>每日签到 {'\uD83D\uDCCB'}</Text>
            <Text style={styles.headerSubtitle}>
              {editing ? '修改今日签到内容' : '花1分钟了解自己的状态'}
            </Text>
          </Animated.View>

          {/* 维度评分 */}
          <View style={styles.content}>
            {DIMENSIONS.map((dim, idx) => (
              <DimensionGroup
                key={dim.key}
                dim={dim}
                value={ratings[dim.key]}
                onSelect={selectRating}
                index={idx}
              />
            ))}

            {/* 备注 */}
            <Animated.View
              entering={FadeInDown.delay(DIMENSIONS.length * 60).duration(400)}
              style={styles.noteWrap}
            >
              <TextInput
                style={styles.noteInput}
                placeholder="今天有什么想记录的吗？（选填）"
                placeholderTextColor={colors.textHint}
                maxLength={MAX_NOTE_LENGTH}
                value={note}
                onChangeText={setNote}
                multiline={true}
                textAlignVertical="top"
                numberOfLines={4}
              />
              <View style={styles.noteCounter}>
                <Text style={styles.noteCounterText}>
                  {note.length} / {MAX_NOTE_LENGTH}
                </Text>
              </View>
            </Animated.View>

            {/* 提交按钮 */}
            <Animated.View
              entering={FadeInDown.delay(DIMENSIONS.length * 60 + 100).duration(400)}
              style={styles.submitWrap}
            >
              <Pressable
                onPress={handleSubmit}
                disabled={!allRated}
                style={({ pressed }) => [
                  styles.submitButton,
                  !allRated && styles.submitButtonDisabled,
                  pressed && allRated && styles.buttonPressed,
                ]}
              >
                <Text
                  style={[
                    styles.submitButtonText,
                    !allRated && styles.submitButtonTextDisabled,
                  ]}
                >
                  {editing ? '保存修改' : '提交签到'}
                </Text>
              </Pressable>
            </Animated.View>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

// ========================
// 样式
// ========================

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  keyboardAvoid: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scrollContent: {
    paddingBottom: spacing['2xl'],
  },

  // 头部
  header: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
  },
  headerTitle: {
    fontFamily: typography.fontFamily,
    fontSize: 24,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  headerSubtitle: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },

  // 内容区
  content: {
    paddingHorizontal: spacing.md,
  },

  // 维度评分组
  dimGroup: {
    marginBottom: spacing.lg,
  },
  dimLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  dimIcon: {
    fontSize: 16,
  },
  dimLabelText: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  ratingRow: {
    paddingVertical: spacing.sm,
  },
  ratingGroup: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  ratingButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingButtonSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  ratingButtonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.92 }],
  },
  ratingButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '600',
    color: colors.textHint,
  },
  ratingButtonTextSelected: {
    color: colors.surface,
  },
  ratingLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  ratingLabelLeft: {
    fontFamily: typography.fontFamily,
    fontSize: 10,
    color: colors.textHint,
  },
  ratingLabelRight: {
    fontFamily: typography.fontFamily,
    fontSize: 10,
    color: colors.textHint,
  },

  // 备注
  noteWrap: {
    marginTop: spacing.lg,
  },
  noteInput: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  noteCounter: {
    alignItems: 'flex-end',
    marginTop: spacing.xs,
    marginRight: spacing.xs,
  },
  noteCounterText: {
    fontFamily: typography.fontFamily,
    fontSize: 11,
    color: colors.textHint,
  },

  // 提交按钮
  submitWrap: {
    marginTop: spacing.lg,
  },
  submitButton: {
    width: '100%',
    paddingVertical: 14,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    ...shadows.md,
  },
  submitButtonDisabled: {
    opacity: 0.5,
    ...shadows.sm,
  },
  submitButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '600',
    color: colors.surface,
  },
  submitButtonTextDisabled: {
    color: colors.surface,
  },
  buttonPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.97 }],
  },

  // 完成卡片
  doneCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing['2xl'],
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    ...shadows.sm,
    marginTop: spacing.xl,
  },
  doneIcon: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  doneTitle: {
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  doneDesc: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 22,
    textAlign: 'center',
  },
  reEditButton: {
    marginTop: spacing.lg,
    paddingVertical: 10,
    paddingHorizontal: 24,
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  reEditButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '600',
    color: colors.surface,
  },

  // 返回按钮
  backButton: {
    marginTop: spacing.lg,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  backButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '500',
    color: colors.textSecondary,
  },
});

// app/src/pages/checkin/checkin.vue
<template>
  <view class="checkin-page">
    <view class="header"><text class="title">每日签到 📋</text><text class="subtitle">{{ view === 'form' ? (editing ? '修改今日签到内容' : '花1分钟了解自己的状态') : '' }}</text></view>
    <!-- 已签到状态 -->
    <view v-if="view === 'done'" class="done-card">
      <text class="done-icon">✅</text>
      <text class="done-title">今日已签到</text>
      <text class="done-desc">你今天已经完成了签到，可以修改或明天继续加油！</text>
      <view class="edit-btn" @tap="startEdit"><text>修改今日签到</text></view>
    </view>
    <!-- 提交成功 -->
    <view v-else-if="view === 'success'" class="done-card">
      <text class="done-icon">🎉</text>
      <text class="done-title">{{ editing ? '修改成功！' : '签到完成！' }}</text>
      <text class="done-desc">{{ encouragement }}</text>
    </view>
    <!-- 签到表单 -->
    <view v-else class="form-area">
      <view v-for="dim in dimensions" :key="dim.key" class="dim-group">
        <text class="dim-label">{{ dim.icon }} {{ dim.label }}</text>
        <view class="rating-row">
          <view v-for="n in 5" :key="n" :class="['rating-btn', ratings[dim.key] === n ? 'rating-active' : '']" @tap="setRating(dim.key, n)"><text>{{ n }}</text></view>
        </view>
        <view class="rating-labels"><text class="label-left">{{ dim.left }}</text><text class="label-right">{{ dim.right }}</text></view>
      </view>
      <view class="note-area">
        <textarea v-model="note" class="note-input" placeholder="今天有什么想记录的吗？（选填）" :maxlength="200" />
      </view>
      <view :class="['submit-btn', allRated ? 'submit-active' : '']" @tap="handleSubmit">
        <text>{{ editing ? '保存修改' : '提交签到' }}</text>
      </view>
    </view>
    <CrisisButton :visible="true" />
  </view>
</template>
<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import CrisisButton from '@/components/crisis-button/crisis-button.vue'
import { useCheckIn } from '@/composables/use-checkin'

const { hasCheckedToday, todayRecord, submitCheckIn } = useCheckIn()

const dimensions = [
  { key: 'sleep', label: '睡眠质量', icon: '😴', left: '很差', right: '很好' },
  { key: 'mood', label: '情绪状态', icon: '😊', left: '低落', right: '愉悦' },
  { key: 'body', label: '身体活力', icon: '🏃', left: '疲惫', right: '充沛' },
  { key: 'motivation', label: '动力水平', icon: '🎯', left: '无', right: '强烈' },
  { key: 'cognition', label: '思维清晰度', icon: '🧠', left: '模糊', right: '清晰' },
  { key: 'social', label: '社交意愿', icon: '👥', left: '回避', right: '主动' },
]

const encouragements = ['✅ 签到成功！记录是康复的第一步 💪', '🌟 很好！你正在了解自己', '🌱 每一天的记录都是成长的种子', '💪 你做得很好，继续保持！', '🌈 感谢你花时间关注自己']
const encouragement = encouragements[Math.floor(Math.random() * encouragements.length)]

const ratings = reactive<Record<string, number>>({})
const note = ref('')
const editing = ref(false)
const view = ref<'done' | 'form' | 'success'>('form')
const allRated = computed(() => dimensions.every(d => ratings[d.key]))

watch(hasCheckedToday, (val) => {
  if (val && !editing.value && view.value !== 'success') view.value = 'done'
}, { immediate: true })

function setRating(key: string, val: number) { ratings[key] = val }
function startEdit() {
  editing.value = true; view.value = 'form'
  if (todayRecord.value) {
    Object.keys(todayRecord.value.dimensions).forEach(k => { ratings[k] = todayRecord.value.dimensions[k] })
    note.value = todayRecord.value.note || ''
  }
}
function handleSubmit() {
  if (!allRated.value) return
  submitCheckIn({ ...ratings }, note.value)
  view.value = 'success'
}
</script>
<style lang="scss" scoped>
.checkin-page { padding: 32rpx; padding-bottom: 180rpx; }
.header { margin-bottom: 32rpx; }
.title { font-size: 44rpx; font-weight: 700; display: block; }
.subtitle { font-size: 30rpx; color: #6B6B6B; margin-top: 8rpx; display: block; }
.done-card { background: #FFFFFF; border-radius: 32rpx; padding: 64rpx 48rpx; text-align: center; box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.06); margin-top: 32rpx; }
.done-icon { font-size: 120rpx; display: block; margin-bottom: 32rpx; }
.done-title { font-size: 44rpx; font-weight: 600; display: block; }
.done-desc { font-size: 30rpx; color: #6B6B6B; margin-top: 16rpx; display: block; }
.edit-btn { margin-top: 48rpx; background: #4A90D9; color: white; border-radius: 16rpx; padding: 20rpx 48rpx; display: inline-block; font-size: 28rpx; font-weight: 600; }
.dim-group { margin-bottom: 40rpx; }
.dim-label { font-size: 32rpx; font-weight: 600; margin-bottom: 16rpx; display: block; }
.rating-row { display: flex; gap: 20rpx; }
.rating-btn { width: 72rpx; height: 72rpx; border-radius: 50%; border: 4rpx solid #E5E2DC; background: #FFFFFF; font-size: 24rpx; font-weight: 600; color: #9B9B9B; display: flex; align-items: center; justify-content: center; }
.rating-active { border-color: #4A90D9; background: #4A90D9; color: white; }
.rating-labels { display: flex; justify-content: space-between; margin-top: 8rpx; }
.label-left, .label-right { font-size: 22rpx; color: #9B9B9B; }
.note-area { margin-bottom: 32rpx; }
.note-input { width: 100%; min-height: 160rpx; padding: 24rpx; border: 3rpx solid #E5E2DC; border-radius: 16rpx; font-size: 28rpx; box-sizing: border-box; background: #FFFFFF; }
.submit-btn { background: #F0EDE7; color: #9B9B9B; border-radius: 24rpx; padding: 28rpx 0; text-align: center; font-size: 30rpx; font-weight: 600; }
.submit-active { background: #4A90D9; color: #fff; }
</style>
